### PR TITLE
feat: add broken link checker

### PR DESCRIPTION
**Pull request by fzipi**
Add a step for checking broken links.

### CODE REVIEW

**Comment by dune73** [comment]
Do I get this right, this is the broken link checker combined with a fix for the broken links?

Also: Why do you remove my author-byline in lots of blog posts?

**Comment by fzipi360** [comment]
> Do I get this right, this is the broken link checker combined with a fix for the broken links?

Yes!
> 
> Also: Why do you remove my author-byline in lots of blog 

> posts?

Because that's the default now! Only wiht your `author:` git username in the post, will create the same author-byline as you had!

**Comment by fzipi** [comment]
> Do I get this right, this is the broken link checker combined with a fix for the broken links?

Yes!
> 
> Also: Why do you remove my author-byline in lots of blog 

> posts?

Because that's the default now! Only wiht your `author:` git username in the post, will create the same author-byline as you had!

**Comment by dune73** [comment]
Good stuff.

So this looks OK for me now, but I did not check each of the 41 files touched in this PR. Should I?

**Comment by fzipi** [comment]
> Good stuff.
> 
> So this looks OK for me now, but I did not check each of the 41 files touched in this PR. Should I?

As you wish. The link was broken when checked, and after the fix is not broken anymore. 🤷

**Pull request merged**
