### PR TITLE
Blog post on releases 4.6.0 and 3.3.6

### PR DESCRIPTION
**Pull request by amonachesi**

### CODE REVIEW

**Comment by dune73** [comment]
Thanks for the blog post.

Some suggestions:
* The standard "Users of the 4.0 and 3.3 release lines are requested to update to the new releases". Or better still: "All users are requested to update to the new releases."
* Hint at the cooperation with ModSecurity, possibly referring their releases.

**Comment by amonachesi** [comment]
Need info on ModSecurity releases. Is it this? https://github.com/owasp-modsecurity/ModSecurity/pull/3239

**Comment by RedXanadu** [comment]
@fzipi I think "lychee" in the GitHub Actions workflow is failing (not sure what this is?):

```
Error:  Error while loading config: Cannot load configuration file `lychee.toml`: No such file or directory (os error 2)
```

**Review by fzipi — APPROVED** [review]

**Comment by amonachesi** [comment]
@fzipi Do you know what's the problem with this failed syntax-check? Seems I've always got this whenever I do a PR.

**Comment by fzipi** [comment]
> @fzipi I think "lychee" in the GitHub Actions workflow is failing (not sure what this is?):
> 
> `` Error: Error while loading config: Cannot load configuration file `lychee.toml`: No such file or directory (os error 2) ``
> 
> Do we want this?

We want this to work.. which it does locally. lychee is a fast link checker. It used to work properly. I'll figure it out why it doesn't work.

**Pull request merged**
