### PR TITLE
Developer portrait for Max

### PR DESCRIPTION
**Pull request by amonachesi**
New blog post with Max's portrait and two pics in a new folder

### CODE REVIEW

**Comment by amonachesi** [comment]
Sorry, commit Create 1 was a test. Don't know how this ended here in the PR ...

**Comment by fzipi** [comment]
@amonachesi Is jp2 a well-known file extension? 🤔

**Comment by dune73** [comment]
Same for jp1.

Otherwise, this looks good. I like the text.

Maybe rethink the lead. To say that he is an important team member despite not being a security expert leaves a somewhat bad taste. I would try to make the lead 100% positive.

**Comment by amonachesi** [comment]
It's jpeg 2000. That's how I got the pics from Max. But you're right, there may be browsers that have a problem with the format. Changed it to jpeg now.

**Comment by amonachesi** [comment]
Let me explain the part with him not being a security expert: I thought this was an important part for other potential future team members who don't think of themselves as security experts.

But I'll change it if you don't like it.

**Comment by dune73** [comment]
How about this:

`Max Leske is not a security expert per se. And maybe that's exactly what makes him such an important CRS core team member. Max is perhaps also the most global member of the team: ...`

**Comment by amonachesi** [comment]
Okay, changed the lead.

I first thought we needed to say **what** he is if not a security expert. But we have _software developer_ in the title, so I'm okay with your proposed changes.

**Review by dune73 — APPROVED** [review]

**Pull request merged**
